services:
  mariadb:
    image: mariadb:11.1.2
    restart: unless-stopped
    volumes:
      - ./infra/volumes/dev/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  symfony-php:
    build:
      context: ./infra/dev/symfony-php
    volumes:
      - ./infra/volumes/dev/composer:/root/.composer
      - ./infra/dev/symfony-php/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
      - ./app:/var/www/app
    environment:
      APP_ENV: dev
    depends_on:
      - mariadb
    tty: true

  symfony-nginx:
    image: nginx:latest
    volumes:
      - ./infra/volumes/dev/logs/nginx:/var/log/nginx
      - ./infra/dev/symfony-nginx/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - symfony-php
    tty: true

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025, 1080:1080 ]
