services:
  mariadb:
    image: mariadb:11.1.2
    restart: unless-stopped
    volumes:
      - ./infra/volumes/dev/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  vulnerable-symfony-php:
    build:
      context: ./infra/dev/vulnerable/symfony-php
    volumes:
      - ./infra/volumes/dev/composer:/root/.composer
      - ./infra/dev/vulnerable/symfony-php/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
      - ./vulnerable/app:/var/www/app
    environment:
      APP_ENV: dev
    depends_on:
      - mariadb
    tty: true

  vulnerable-symfony-nginx:
    image: nginx:latest
    volumes:
      - ./infra/volumes/dev/logs/nginx:/var/log/nginx
      - ./infra/dev/vulnerable/symfony-nginx/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./vulnerable/app:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - vulnerable-symfony-php
    tty: true

  secure-symfony-php:
    build:
      context: ./infra/dev/secure/symfony-php
    volumes:
      - ./infra/volumes/dev/composer:/root/.composer
      - ./infra/dev/secure/symfony-php/project.ini:/usr/local/etc/php/conf.d/project.ini:ro
      - ./secure/app:/var/www/app
    environment:
      APP_ENV: dev
    depends_on:
      - mariadb
    tty: true

  secure-symfony-nginx:
    image: nginx:latest
    volumes:
      - ./infra/volumes/dev/logs/nginx:/var/log/nginx
      - ./infra/dev/secure/symfony-nginx/virtualhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./secure/app:/var/www/app
    ports:
      - "81:80"
    depends_on:
      - secure-symfony-php
    tty: true

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025, 1080:1080 ]
