<?php

namespace ContainerS8y4101;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RWUCyAEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RWUCyAE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RWUCyAE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'inscription' => ['privates', '.errored..service_locator.RWUCyAE.App\\Entity\\Inscription', NULL, 'Cannot autowire service ".service_locator.RWUCyAE": it needs an instance of "App\\Entity\\Inscription" but this type has been excluded in "config/services.yaml".'],
        ], [
            'inscription' => 'App\\Entity\\Inscription',
        ]);
    }
}
