<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEKsiIAy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEKsiIAy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEKsiIAy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEKsiIAy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEKsiIAy\App_KernelDevDebugContainer([
    'container.build_hash' => 'EKsiIAy',
    'container.build_id' => '2a3dc5c0',
    'container.build_time' => 1733584870,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEKsiIAy');
