<?php

namespace ContainerS8y4101;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MZW99cService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mZW_99c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mZW_99c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'metier' => ['privates', '.errored..service_locator.mZW_99c.App\\Entity\\Metier', NULL, 'Cannot autowire service ".service_locator.mZW_99c": it needs an instance of "App\\Entity\\Metier" but this type has been excluded in "config/services.yaml".'],
        ], [
            'metier' => 'App\\Entity\\Metier',
        ]);
    }
}
