<?php

namespace ContainerS8y4101;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RvAJznUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RvAJznU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RvAJznU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'metierRepository' => ['privates', 'App\\Repository\\MetierRepository', 'getMetierRepositoryService', true],
        ], [
            'metierRepository' => 'App\\Repository\\MetierRepository',
        ]);
    }
}
