<?php

namespace ContainerS8y4101;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FKOtdlGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FKOtdlG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FKOtdlG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'metier' => ['privates', '.errored..service_locator.FKOtdlG.App\\Entity\\Metier', NULL, 'Cannot autowire service ".service_locator.FKOtdlG": it needs an instance of "App\\Entity\\Metier" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'metier' => 'App\\Entity\\Metier',
        ]);
    }
}
