<?php

namespace ContainerS8y4101;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FKOtdlG.App\Entity\Metier' shared service.
     *
     * @return \App\Entity\Metier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FKOtdlG": it needs an instance of "App\\Entity\\Metier" but this type has been excluded in "config/services.yaml".');
    }
}
