<?php

namespace ContainerS8y4101;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecteurTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SecteurType' shared autowired service.
     *
     * @return \App\Form\SecteurType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SecteurType.php';

        return $container->privates['App\\Form\\SecteurType'] = new \App\Form\SecteurType();
    }
}
