<?php

namespace ContainerEKsiIAy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rl1maqfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rl1maqf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rl1maqf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'atelier' => ['privates', '.errored..service_locator.rl1maqf.App\\Entity\\Atelier', NULL, 'Cannot autowire service ".service_locator.rl1maqf": it needs an instance of "App\\Entity\\Atelier" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'atelier' => 'App\\Entity\\Atelier',
            'entityManager' => '?',
        ]);
    }
}
