<?php

namespace ContainerEKsiIAy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QFLS_IeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qFLS.ie' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qFLS.ie'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lycee' => ['privates', '.errored..service_locator.qFLS.ie.App\\Entity\\Lycee', NULL, 'Cannot autowire service ".service_locator.qFLS.ie": it needs an instance of "App\\Entity\\Lycee" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lycee' => 'App\\Entity\\Lycee',
        ]);
    }
}
