<?php

namespace ContainerEKsiIAy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Value_Sh66iR6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.value.sh66iR6' shared service.
     *
     * @return \mixed
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.value.sh66iR6'] = (\dirname(__DIR__, 4).'/public/uploads/images');
    }
}
